[project]
name = "hdrezka-app-unofficial"
version = "0.1.0"
description = "Unofficial HDRezka App"
requires-python = ">=3.13"
dependencies = [
    "aiohttp==3.13.1",
    "beautifulsoup4==4.14.2",
    "hdrezka>=4.0.3",
    "lxml==6.0.2",
    "pyside6==6.10.0",
    "qasync==0.28.0",
]
